apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-aks-demo.fullname" . }}
  labels:
    {{- include "go-aks-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "go-aks-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-aks-demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: go-aks-demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP

          env:
            - name: PORT
              value: "{{ .Values.containerPort }}"

            - name: ENVIRONMENT
              value: "{{ .Values.environment }}"

            - name: APP_VERSION
              value: "{{ .Values.image.tag }}"

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}