replicaCount: 2

image:
  repository: abdulacr.azurecr.io/go-aks-demo
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

containerPort: 8080

environment: dev

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

probes:
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 10

  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 20