name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  REGISTRY: abdulacr.azurecr.io
  IMAGE_NAME: go-aks-demo

jobs:
  test:
    name: Test Go Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Format check
        run: |
          test -z "$(gofmt -l .)"

      - name: Run tests
        run: go test ./...

  docker:
    name: Build and Push Image
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Azure authentication
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name abdulacr

      - name: Build Docker image
        run: |
          docker build \
            -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}